### ISSUE TITLE
Do not re-define the "I confirm the quiz submission in the modal dialog" step for Behat

### ISSUE THREAD

**Issue by lucaboesch** [dbauer-ets/moodle-qtype_formulas#131]
Hi

When running another qtype's behat tests I get a 
`
Step "/^I confirm the quiz submission in the modal dialog$/" is already defined in behat_qtype_formulas::i_confirm_the_quiz_submission_in_the_modal_dialog()
`
error.

**Comment by PhilippImhof** [comment]
Yes, I saw that when working on the archive report plugin. This only happens when both plugins exist. That's because I (and probably you too) did not respect the recommendation to have the plugin name in the step: `I confirm ... in the modal dialog for the qtype_formulas plugin` or something like that.

I did not fix it back then, because those tests are for dev only and are mostly used on clean installs. But I might do it, now that someone else stumbled over it.
