### ISSUE TITLE
DynamicCourseware.org status

### ISSUE THREAD

**Issue by zmartinovic** [dbauer-ets/moodle-qtype_formulas#92]
Do you have any information when DynamicCourseware.org site could be back online? Many of our teachers like and depend on the documentation on your site :)

Thanks in advanced

**Comment by dbauer-ets** [comment]
Here is the latest news.

Initially, the site had to be offline for three hours for a major update. But it's still offline after more than two weeks. The problem is that the computer analyst who was supposed to help me is busy with another urgent project.

However, he assured me that he will be able to update the site in the next few days. Hence it should be back online this week, if not next week. Hopefully...

In the meantime, I started looking for help elsewhere, posting a job offer on Moodle jobs. The ad hasn't appeared yet because there are delays before it's approved.

**Comment by dbauer-ets** [comment]
The DynamicCourseware.org website is now running on Moodle 4.2 and is fully functional again.
