### ISSUE TITLE
PHP 8.1

### ISSUE THREAD

**Issue by ewallah** [dbauer-ets/moodle-qtype_formulas#99]
## Description of bug / unexpected behavior

PHP 8.1 can be used with Moodle 4.1 and 4.2. But certain functions throw deprecation warnings (until PHP 9, then they will throw errors). 

## How to reproduce the issue

1. Install PHP 8.1
2. Run PHPUnit tests
3. Run Behat tests

<details><summary>Warnings</summary>

```
PHP Deprecated:  stripcslashes(): Passing null to parameter #1 ($string) of type string is deprecated in variables.php on line 665

PHP Deprecated:  explode(): Passing null to parameter #2 ($string) of type string is deprecated in variables.php on line 603
```

</details>

## Environment

<details><summary>System Details</summary>

* Moodle version: 4.1.3+ (Build: 20230526)
* Plugin version: 2023042400
* PHP version:  8.1.18

</details>

**Comment by PhilippImhof** [comment]
Thanks. I think you are not using the most recent version, because this was fixed here:

https://github.com/FormulasQuestion/moodle-qtype_formulas/commit/74ff90d1abd52dce639c872b04b59f7bd5d90d36#diff-42e69e4d6e8821b780430ca7c84289e9fed460b1893311c95e43824ff8a2b09e

Also, that entire part of the code base is going to disappear before the end of this year, so probably way before PHP 9 is out and certainly before it is supported by Moodle.
